#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'DE1_SoC' in
 * file './DE1_SoC.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'jtag_uart_0', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_0_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_0_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_0_COMPONENT_NAME jtag_uart_0
#define JTAG_UART_0_BASE 0x0
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_END 0x7
#define JTAG_UART_0_IRQ 0
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8

/*
 * Macros for device 'sysid_qsys_0', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_0_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_0_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_0_COMPONENT_NAME sysid_qsys_0
#define SYSID_QSYS_0_BASE 0x8
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_END 0xf
#define SYSID_QSYS_0_ID 0
#define SYSID_QSYS_0_TIMESTAMP 1631220844

/*
 * Macros for device 'displays_ctrl', class 'altera_avalon_pio'
 * The macros are prefixed with 'DISPLAYS_CTRL_'.
 * The prefix is the slave descriptor.
 */
#define DISPLAYS_CTRL_COMPONENT_TYPE altera_avalon_pio
#define DISPLAYS_CTRL_COMPONENT_NAME displays_ctrl
#define DISPLAYS_CTRL_BASE 0x30000
#define DISPLAYS_CTRL_SPAN 16
#define DISPLAYS_CTRL_END 0x3000f
#define DISPLAYS_CTRL_BIT_CLEARING_EDGE_REGISTER 0
#define DISPLAYS_CTRL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DISPLAYS_CTRL_CAPTURE 0
#define DISPLAYS_CTRL_DATA_WIDTH 6
#define DISPLAYS_CTRL_DO_TEST_BENCH_WIRING 0
#define DISPLAYS_CTRL_DRIVEN_SIM_VALUE 0
#define DISPLAYS_CTRL_EDGE_TYPE NONE
#define DISPLAYS_CTRL_FREQ 50000000
#define DISPLAYS_CTRL_HAS_IN 0
#define DISPLAYS_CTRL_HAS_OUT 1
#define DISPLAYS_CTRL_HAS_TRI 0
#define DISPLAYS_CTRL_IRQ_TYPE NONE
#define DISPLAYS_CTRL_RESET_VALUE 0

/*
 * Macros for device 'blinker_0', class 'blinker'
 * The macros are prefixed with 'BLINKER_0_'.
 * The prefix is the slave descriptor.
 */
#define BLINKER_0_COMPONENT_TYPE blinker
#define BLINKER_0_COMPONENT_NAME blinker_0
#define BLINKER_0_BASE 0x40000
#define BLINKER_0_SPAN 2
#define BLINKER_0_END 0x40001


#endif /* _ALTERA_HPS_0_H_ */
